# Generated by Django 2.1.3 on 2018-11-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thing.Thing')),
            ],
        ),
    ]
