# Generated by Django 2.1.3 on 2018-11-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0003_auto_20181106_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=1, upload_to='project_img'),
            preserve_default=False,
        ),
    ]
